@startuml
title "Базовый сценарий."
autonumber

actor "Оператор" as operator
participant "Наземный центр\n управления" as ChatGPT
participant "ОрВД" as orvd
participant "Группа\n дронов" as dronegroup
participant "1. Управление\n связью" as 1
participant "2. Обработчик\n входящих данных" as 2
participant "4. Контроль выполнения\n задания -\n взаимодействие" as 4
participant "5. Контроль выполнения\n задания -\n полет" as 5
participant "6. Контроль выполнения\n задания -\n Обнаружение" as 6
participant "7. Управление\n полетом" as 7
participant "8. Навигация" as 8
participant "9. GPS" as 9
participant "10. LPS" as 10
participant "11. Управление\n Двигателями" as 11
participant "12. Технические\n данные" as 12
participant "13. Контроль\n батареи" as 13
participant "14. Аварийная\n посадка" as 14
participant "15. Детектор \nобнаружения тип А" as 15

actor "Человек" as human

group Инициализация задания
ChatGPT -> orvd: Регистрация полётного задания
orvd --> ChatGPT: Одобрение полётного задания
ChatGPT -> dronegroup: Данные о новом задании
dronegroup --> ChatGPT : Статус о принятом задании
dronegroup -> orvd: Регистрация группы
orvd --> dronegroup : Регистрация выполнена
ChatGPT -> 1: Данные о новом задании
1 -> 2: Данные о задании, от кого и куда
2 -> 4: Данные о задании
4 -> 5: Данные о полетной области
4 --> 2: Статус о принятом задании задании
2 --> 1: Статус о принятом задании задании
1 --> ChatGPT: Статус о принятом задании
end group

group Выполнение задания
    4 -> 5: Данные о подзадании
    5 -> 7: Полетное подзадание
    group loop [Полёт]
        7 -> 11: Данные о движении исходя из подзадания
        11 -> 12: Данные о двигателях
        13 -> 12: Данные о батареи
        12 -> 7: Технические данные
        7 --> 14: Статус аварийной посадки
        9 -> 8: Координаты
        10 -> 8: Координаты
        8 -> 7: Достоверные координаты
        7 --> 5: Статус, данные о полёте

    end group

    group loop [Обнаружение]
        15 --> human: Обнаружение субъекта
        15 -> 6: Данные об обнаружении
        6 -> 5: Запрос данных о местоположении
        5 --> 6: Данные о местоположении
        6 -> 4: Данные об обнаружении
        4 -> 2: Данные об обнаружении, данные о новом подзадании
        2 -> 1: Данные об обнаружении, данные о новом подзадании
        1 -> dronegroup: Данные об обнаружении, данные о новом подзадании
        1 -> ChatGPT: Данные об обнаружении
    end group
    group Новое подзадание
        dronegroup -> 1: Новое подзадание
        1 -> 2: новое подзадание
        2 -> 4: новое подзадание
        4 -> 5: полетные данные о новом подзадании
        5 -> 7: новое полетное подзадание
        note right
            Дальше повторяется цикл "Полет"
        endnote
    end group

end group

group Завершение задания
    dronegroup -> 1: Данные о завершении задания
    1 -> 2: Данные о завершении задания
    2 -> 4: Данные о завершении задания
    4 -> 5: Данные о завершении задания
    5 -> 7: Возвращение на базу
    note right
        Дальше повторяется цикл "Полет"
    endnote
end group
@enduml