@startuml
title "Базовый сценарий."
autonumber

actor "Оператор" as operator
participant "Наземный центр\n управления" as ChatGPT
participant "ОрВД" as orvd
participant "Группа\n дронов" as dronegroup
participant "1. Управление\n связью" as 1
participant "2. Обработчик\n входящих данных" as 2
participant "4. Контроль выполнения\n задания -\n взаимодействие" as 4
participant "5. Контроль выполнения\n задания -\n полет" as 5
participant "6. Контроль выполнения\n задания -\n Обнаружение" as 6
participant "7. Управление\n полетом" as 7
participant "8. Навигация" as 8
participant "9. GPS" as 9
participant "10. LPS" as 10
participant "11. Управление\n Двигателями" as 11
participant "12. Технические\n данные" as 12
participant "13. Контроль\n батареи" as 13
participant "14. Аварийная\n посадка" as 14
participant "15. Детектор \nобнаружения тип А" as 15

actor "Человек" as human

ChatGPT -> 1: Задание
1 -> 2: данные о задании, от кого и куда
2 -> 4: данные о задании
4 -> 5: данные о полетной области

group Выполнение задания
    4 -> 5: какое именно задание
    5 -> 7: полетное задание
    group loop [Полёт]
        7 -> 11: данные о движении исходя из задания
        11 -> 12: данные о двигателях
        13 -> 12: данные о батареи
        12 -> 7: технические данные
        7 --> 14: статус аварийной посадки
        9 -> 8: координаты
        10 -> 8: координаты
        8 -> 7: достоверные координаты
        7 --> 5: Статус

    end group

    group loop [Обнаружение]
        15 --> human: обнаружение субъекта
        15 -> 6: данные об обнаружении
        5 -> 6: положение
        6 -> 4: данные об обнаружении
        4 -> 2: данные об обнаружении, данные о новом задании
        4 -> 1: данные об обнаружении, данные о новом задании
        1 -> ChatGPT: данные об обнаружении
    end group
    group Новое задание
        1 -> 2: новое задание
        2 -> 4: новое задание
        4 -> 5: полетные данные о новом задании
        4 -> 5: выполнять это задание
        5 -> 7: новое полетное задание
        note right
            И опять начинается полет
        endnote
    end group


end group




@enduml